#!/bin/bash

source $(dirname "$0")/lib/_bool;
source $(dirname "$0")/lib/_echo;
source $(dirname "$0")/lib/_file;
source $(dirname "$0")/lib/_print;

source $(dirname "$0")/shell/_options;
source $(dirname "$0")/out/print_head;
source $(dirname "$0")/out/print_user_env $USER $(uname) $SHELL;
print_information_message $(source $(dirname "$0")/shell/_setup);
source $(dirname "$0")/out/print_foot_fail;
source $(dirname "$0")/out/print_foot_success;
